### PR TITLE
Upgrade leapc

### LINKED ISSUE #427: Fix Image Distortion in LeapC

### LINKED ISSUE #428: Upgrade to the latest LeapC

### PR DESCRIPTION
**Pull request by Amarcolina**
- Change api usage to match new api, only small changes like removing IsEmbedded
 - Added a better unit test to make sure that TransformCopy produces a binary equivalent frame when using the identity transform.  Should help copy errors in the future.
 - Upgraded IE to make sure to fill all fields of the new data layout
 - Upped IE version
 - Updated all dlls to newest version

fixes #427
fixes #428

@jselstad 
@ajohnston33 
@jo3w4rd

### CODE REVIEW

**Comment by ajohnston33** [comment]
This needs to merge in parallel with http://sf-github.leap.corp/leapmotion/platform/pull/6859
I will be building new dlls shortly, a version check will fail without them.

**Comment by Amarcolina** [comment]
@ajohnston33 could you push the updated dlls into this branch when you are finished?

**Comment by ajohnston33** [comment]
Those dlls are added.  This should be ready to merge.

**Comment by jselstad** [comment]
Blocked on http://sf-github.leap.corp/leapmotion/platform/pull/6870

LeapTemporalWarping (and a bunch of other things) are horribly broken when using Rigel if this is not applied.

**Comment by jselstad** [comment]
Rigel-friendly .dlls are in and it works!

**Pull request merged**
