### PR TITLE
Fix playmode tests

### PR DESCRIPTION
**Pull request by Amarcolina**
Playmode tests got broken due to the code for them living inside of an ifdef that only gets enabled when we want to build tests.  This caused our refactoring to fail to find all of the relevant code, breaking the tests when the code was enabled again.

Furthermore, there are some tests that are not passing that I will need the help of @nickjbenson to fix.  It might be related to some of the interaction engine test prefabs, which have some unbound scripts that may or may not be important?

To test:
 - [ ] Playmode tests must compile and pass

### CODE REVIEW

**Comment by nickjbenson** [comment]
Alright, IE tests work for me now, I cleaned up a missing script reference in the test rig prefabs but the key fix appeared to be ensuring that the test recording didn't auto-play as soon as the test began.

**Comment by nickjbenson** [comment]
However, GR play-mode tests are failing for me, so that task remains for this PR. @Amarcolina

**Comment by Amarcolina** [comment]
What tests are failing for you?  All tests pass for me.  What version of Unity did you use for testing?

**Comment by nickjbenson** [comment]
I used 2017.3.0f3. I'll run them again in the morning and report back.

**Comment by Amarcolina** [comment]
Arg, I see, they are failing on and off for me, and different _editor window configurations_ are making the issue better or worse.  Arggg

**Pull request merged**
