### PR TITLE
Added Low Poly Hands to Android Module

### PR DESCRIPTION
**Pull request by jselstad**
Swapped Capsule Hands out for LoPolyHands (also copied them from the Hands module into the Android Module)

NOTE: LoPolyHand Scripts are duplicated (with different names)!
This is not a permanent solution! At some point we're going to have the talk (about intermodule dependencies).

### CODE REVIEW

**Comment by testmasterbright** [comment]
I presume that the 5.3.5 in the branch name signifies that we won't be able to use it in 5.3.4 Unity? If so, this causes us to now recommend using the beta version of Unity because of the World Canvas issue making the FPS counter disappear.

**Comment by jselstad** [comment]
Actually It's there because everything was totally broken when I tried
doing it in 5.4b23 and importing it back to 5.3.5

So I redid all the changes in 5.3.5 and named the branch that to signify
which version all of this was done.

The changes I made have nothing to do with the canvas...  If that was
broken before, it's probably still broken...

On Tue, Jun 28, 2016 at 4:49 PM, testmasterbright <notifications@github.com>
wrote:

> I presume that the 5.3.5 in the branch name signifies that we won't be
> able to use it in 5.3.4 Unity? If so, this causes us to now recommend using
> the beta version of Unity because of the World Canvas issue making the FPS
> counter disappear.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/leapmotion/UnityModules/pull/319#issuecomment-229217904>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARjUfnGGOdRCIPHRUYtifffawJ7QIr__ks5qQbL-gaJpZM4JAnkI>
> .
>

-- 
NOTE: The information in this message and any attachments is confidential 
information intended only for the individual to whom it is addressed.  If 
you are not the intended recipient, any distribution of this message or its 
attachments is prohibited.  If you have received this email in error, 
please immediately notify us and delete the message.  Thank you.

**Comment by testmasterbright** [comment]
I meant that anyone that wants to use the canvas (like our FPS counter) will now need to build in the latest 5.4 beta because the hand requires 5.3.5 which has the broken world canvas. Previous releases of Android they were able to use 5.3.4f1 which did not have the world canvas issue.

**Comment by jselstad** [comment]
Hmm, hopefully this doesn't break it going back to 5.3.4f1?  No explicit
reason why it would...

Alternately, 5.3.6 is in the pipeline which will fix the world canvas issue
as well...

On Tuesday, June 28, 2016, testmasterbright <notifications@github.com>
wrote:

> I meant that anyone that wants to use the canvas (like our FPS counter)
> will now need to build in the latest 5.4 beta because the hand requires
> 5.3.5 which has the broken world canvas. Previous releases of Android they
> were able to use 5.3.4f1 which did not have the world canvas issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/leapmotion/UnityModules/pull/319#issuecomment-229219280>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARjUfkQFFrWsM9ZsUELOnN5z6yjhZXuDks5qQbUDgaJpZM4JAnkI>
> .
>

-- 
NOTE: The information in this message and any attachments is confidential 
information intended only for the individual to whom it is addressed.  If 
you are not the intended recipient, any distribution of this message or its 
attachments is prohibited.  If you have received this email in error, 
please immediately notify us and delete the message.  Thank you.

**Comment by testmasterbright** [comment]
I'll try it in 5.3.4f1 but at worst this is just a known issue to be documented

**Pull request merged**
