### PR TITLE
restructure gear vr related stuff to android module

### PR DESCRIPTION
**Pull request by veronicaz41**
DO NOT MERGE YET
This is supposed to work the same as branch orion-gearvr. After this is merged, we can get rid of that branch.
- [x] depends on https://github.com/leapmotion/UnityModules/pull/174
- [ ] Remove references to low poly capsule hand, use the new one added in #174
- [ ] remove signature files and figure out where to put them
- [ ] need to test on gear vr
* When build for gear vr, need to go to player settings -> other settings, and enable "Multithreaded Rendering"

### CODE REVIEW

**Comment by Amarcolina** [comment]
This PR should wait for #174.  The low poly hands introduced by this PR are superseded by the upgraded capsule hands in #174

**Comment by Amarcolina** [comment]
We also should probably not check in the signatures for half a dozen devices either.

**Comment by testmasterbright** [comment]
At least 5 of them are the in house phones. What is the harm of leaving them in?

**Comment by Amarcolina** [comment]
Ok this branch has conflicts now, you will need to remove references to the low poly capsule hand.  #174 added the functionality needed to allow us to use the default capsule hand instead.

**Comment by Amarcolina** [comment]
It's also the case that we should not be having cross-module references.  Currently there are references to the PinchUtility module, which should be removed.

**Comment by Amarcolina** [comment]
Not sure if this PR is being worked on anymore?  Should it be closed for now?

**Comment by veronicaz41** [comment]
This is too out dated. Will open another PR to address this later. Closing for now.

**Pull request closed without merging**
