### PR TITLE
Add Data/Render fps

### PR DESCRIPTION
**Pull request by hham**
Data fps and render fps are added in Leap_Hands_Demo_HMD scene.

### CODE REVIEW

**Comment by Amarcolina** [comment]
We should create a separate FPS component to keep the responsibilities of HandController simple and contained.

**Comment by jdonald** [comment]
I'll continue building off this branch for debugging. Sounds like we don't plan to merge it upstream, and will hold out for a separate FPS component?

It has some Debug prints and bad indentation left over here too :)

**Comment by testmasterbright** [comment]
Seems like this would be easy to port over to the VR Visualizer, no?

**Comment by hham** [comment]
Does VR Visualizer mean RiggedHandVisualizer?
Agree. This doesn't need to be merged. Let's just keep it in a separate branch.

**Comment by testmasterbright** [comment]
VR Visualizer Unity project: https://github.com/leapmotion/UnityModules/tree/master/Assets/LeapMotionModules/VRVisualizer

**Comment by hham** [comment]
Thank you for letting me know. It should be easy.
Closing Now.

**Pull request closed without merging**
