### PR TITLE
Release 4.3.4

### PR DESCRIPTION
**Pull request by Amarcolina**
Release for Core 4.3.4
 - Updated to support Unity 2017.3
 - Renamed IHandModel to HandModelBase
 - Improved physics interpolation in LeapServiceProvider
 - Fixed bug where graphic renderer inspector would fail when the user uses unpacked sprites.
 - Added callouts to notify users that unpacked sprites are not supported in the Graphic Renderer.
 - Added a new Pose struct to keep track of a point in space with a position and an orientation
 - Added extra operations for Query (Conversion, Repeat, Uniform, and default Sequences)
 - Added the CurveBounds attribute for AnimationCurve values
 - Added default AnimationCurve types
 - Added many Rect utilities (area, expansion, encapsulation...)
 - Added DrawPosition to the RuntimeGizmos
 - Improved ImplementsInterface attribute (now supports ScriptableObject)
 - Added cubic hermite splines (with float, Vector2, and Vector3 variants)
 - Added a swizzle class to allow you to swizzle Vector2, Vector3, and Vector4 structs
 - Added many general utility functions / fixed bugs

Release for Graphic Renderer 0.1.2
 - Updated to support Unity 2017.3
 - Allowed you to disable or enable a graphic without detaching or re-attaching the graphic.
 - Disabled graphics are no longer visible!
 - Disabling and Enabling graphics is now lightning fast!
 - Improved dirty detection to reduce rebuild situations
 - Fixed several edge cases

Release for Interaction Engine 1.1.1
 - Updated to support Unity 2017.3
 - Added ability to force a controller to grasp an object
 - Fix a bug where the physics representation of the hands would explode sometimes when switching between curved spaces
 - Added the SwapGrasp function and a corresponding example scene, allowing you swap a grasped object with another object in the scene.
 - Correctly account for the Physics.autoSyncTransforms state during the Interaction Manager update.

Release for UI Input 1.2.2
 - Updated to support Unity 2017.3

Release for Hands 2.1.3
 - Updated to support Unity 2017.3
 - Renamed IHandModel to HandModelBase

Release for Detection Examples 1.0.5
 - Updated to support Unity 2017.3

Release for Attachments 1.0.6
 - Updated to support Unity 2017.3

### CODE REVIEW

**Comment by testmasterbright** [comment]
We have some pressing tasks to wrap up before CES so we won't be able to start looking at this until like Monday.

**Comment by nickjbenson** [comment]
@Amarcolina, I'm seeing this error after exporting the Graphic Renderer via the Package module and loading it into a clean Unity 2017.3 empty scene (CoreWithAndroid imported first, then GR):

```
ArgumentException: Could not get atlas data - Sprite is not packed.
Leap.Unity.GraphicalRenderer.SpriteAtlasUtil.getAtlasedUvsEditor (UnityEngine.Sprite sprite) (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/SpriteUtil.cs:71)
Leap.Unity.GraphicalRenderer.SpriteAtlasUtil.GetAtlasedUvs (UnityEngine.Sprite sprite) (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/SpriteUtil.cs:59)
Leap.Unity.GraphicalRenderer.SpriteAtlasUtil.GetAtlasedRect (UnityEngine.Sprite sprite) (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/SpriteUtil.cs:40)
Leap.Unity.GraphicalRenderer.SpriteAtlasUtil.<ShowInvalidSpriteWarning>m__1 (UnityEngine.Sprite s) (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/SpriteUtil.cs:29)
Leap.Unity.Query.SelectOp`3[UnityEngine.Sprite,UnityEngine.Rect,Leap.Unity.Query.WhereOp`2[UnityEngine.Sprite,Leap.Unity.Query.SelectManyOp`4[Leap.Unity.GraphicalRenderer.LeapSpriteFeature,UnityEngine.Sprite,Leap.Unity.Query.OfTypeOp`3[Leap.Unity.GraphicalRenderer.LeapGraphicFeatureBase,Leap.Unity.GraphicalRenderer.LeapSpriteFeature,Leap.Unity.Query.QueryConversionExtensions+ListQueryOp`1[Leap.Unity.GraphicalRenderer.LeapGraphicFeatureBase]],Leap.Unity.Query.SelectOp`3[Leap.Unity.GraphicalRenderer.LeapSpriteData,UnityEngine.Sprite,Leap.Unity.Query.QueryConversionExtensions+ListQueryOp`1[Leap.Unity.GraphicalRenderer.LeapSpriteData]]]]].TryGetNext (UnityEngine.Rect& t) (at Assets/LeapMotion/Core/Scripts/Query/Select.cs:27)
Leap.Unity.Query.WhereOp`2[UnityEngine.Rect,Leap.Unity.Query.SelectOp`3[UnityEngine.Sprite,UnityEngine.Rect,Leap.Unity.Query.WhereOp`2[UnityEngine.Sprite,Leap.Unity.Query.SelectManyOp`4[Leap.Unity.GraphicalRenderer.LeapSpriteFeature,UnityEngine.Sprite,Leap.Unity.Query.OfTypeOp`3[Leap.Unity.GraphicalRenderer.LeapGraphicFeatureBase,Leap.Unity.GraphicalRenderer.LeapSpriteFeature,Leap.Unity.Query.QueryConversionExtensions+ListQueryOp`1[Leap.Unity.GraphicalRenderer.LeapGraphicFeatureBase]],Leap.Unity.Query.SelectOp`3[Leap.Unity.GraphicalRenderer.LeapSpriteData,UnityEngine.Sprite,Leap.Unity.Query.QueryConversionExtensions+ListQueryOp`1[Leap.Unity.GraphicalRenderer.LeapSpriteData]]]]]].TryGetNext (UnityEngine.Rect& t) (at Assets/LeapMotion/Core/Scripts/Query/Where.cs:26)
Leap.Unity.Query.QueryWrapper`2[UnityEngine.Rect,Leap.Unity.Query.WhereOp`2[UnityEngine.Rect,Leap.Unity.Query.SelectOp`3[UnityEngine.Sprite,UnityEngine.Rect,Leap.Unity.Query.WhereOp`2[UnityEngine.Sprite,Leap.Unity.Query.SelectManyOp`4[Leap.Unity.GraphicalRenderer.LeapSpriteFeature,UnityEngine.Sprite,Leap.Unity.Query.OfTypeOp`3[Leap.Unity.GraphicalRenderer.LeapGraphicFeatureBase,Leap.Unity.GraphicalRenderer.LeapSpriteFeature,Leap.Unity.Query.QueryConversionExtensions+ListQueryOp`1[Leap.Unity.GraphicalRenderer.LeapGraphicFeatureBase]],Leap.Unity.Query.SelectOp`3[Leap.Unity.GraphicalRenderer.LeapSpriteData,UnityEngine.Sprite,Leap.Unity.Query.QueryConversionExtensions+ListQueryOp`1[Leap.Unity.GraphicalRenderer.LeapSpriteData]]]]]]].Any () (at Assets/LeapMotion/Core/Scripts/Query/DirectQueryOps.cs:69)
Leap.Unity.Query.QueryWrapper`2[UnityEngine.Rect,Leap.Unity.Query.SelectOp`3[UnityEngine.Sprite,UnityEngine.Rect,Leap.Unity.Query.WhereOp`2[UnityEngine.Sprite,Leap.Unity.Query.SelectManyOp`4[Leap.Unity.GraphicalRenderer.LeapSpriteFeature,UnityEngine.Sprite,Leap.Unity.Query.OfTypeOp`3[Leap.Unity.GraphicalRenderer.LeapGraphicFeatureBase,Leap.Unity.GraphicalRenderer.LeapSpriteFeature,Leap.Unity.Query.QueryConversionExtensions+ListQueryOp`1[Leap.Unity.GraphicalRenderer.LeapGraphicFeatureBase]],Leap.Unity.Query.SelectOp`3[Leap.Unity.GraphicalRenderer.LeapSpriteData,UnityEngine.Sprite,Leap.Unity.Query.QueryConversionExtensions+ListQueryOp`1[Leap.Unity.GraphicalRenderer.LeapSpriteData]]]]]].Any (System.Func`2 predicate) (at Assets/LeapMotion/Core/Scripts/Query/DirectQueryOps.cs:76)
Leap.Unity.GraphicalRenderer.SpriteAtlasUtil.ShowInvalidSpriteWarning (IList`1 features) (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/SpriteUtil.cs:30)
Leap.Unity.GraphicalRenderer.LeapGuiGroupEditor.drawSpriteWarning () (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Editor/LeapGraphicGroupEditor.cs:272)
Leap.Unity.GraphicalRenderer.LeapGuiGroupEditor.DoGuiLayout (UnityEditor.SerializedProperty groupProperty) (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Editor/LeapGraphicGroupEditor.cs:141)
Leap.Unity.GraphicalRenderer.LeapGraphicRendererEditor.OnInspectorGUI () (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Editor/LeapGraphicRendererEditor.cs:89)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1245)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by nickjbenson** [comment]
Alright, this has my approval now!

**Comment by nickjbenson** [comment]
Comment from Steve (working on it soon):
> When importing the package into a Unity project, libLeapC.so can be found in Assets > Leap Motion > Core > Plugins > x86_64. As an Android file, this should not be present.

**Pull request merged**
